Airline.UI/Controllers/FligthsController.cs
using System.Linq;
using System.Linq.Dynamic.Core;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Airline.DAL.Airline_Db_Context;
using Airline.DAL.IRepository;
using Airline.DAL.Models;
using Airline_Yurchenko.Areas.AccountFilters;
using Airline_Yurchenko.SortExtentions;
using Airline_Yurchenko.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace Airline_Yurchenko.Controllers
{
    public class FligthsController : Controller
    {
        private readonly ILoggerManager _logger;
        private readonly IRepositoryWrapper _repositoryWrapper;
        
        public FligthsController(IRepositoryWrapper repositoryWrapper, ILoggerManager logger)
        {
            _repositoryWrapper = repositoryWrapper;
            _logger = logger;
        }
        [HttpGet]
        public IActionResult GetProblem()
        {
            var source = _repositoryWrapper.RequsetRepository.Get().ToList();
            var airlineContext = _repositoryWrapper.RequsetRepository.Get()
                .GroupBy(u => u.SignIn, (key, items) => new RequestViewModel
                {
                    Sig = key,
                    Cost = items.Count(),
                })
                .ToList();

            var model = new GroupedRequestViewModel
            {
                Items = airlineContext,
                Total = source.Count
            };
            _logger.LogInfo($"Returned all requests from admin.");
            return View(model);
        }

        public async Task<IActionResult> GetListProblem(string id)
        {
            var source = _repositoryWrapper.RequsetRepository.GetListProblem(id);
            return View(await source.ToListAsync());
        }
        // GET: Fligths

        [AllowAnonymous]
        public async Task<IActionResult> Index(string sort)
        {
            sort ??= "Name_Fligth";
            if (IsUser())       //get all flight for all users
                return View(await _repositoryWrapper.FligthRepository.GetFligthAllUsers().SortDynamic(sort).ToDynamicListAsync<Fligth>());
            return User.IsInRole("admin")                     //get flight for users with role
                ? View(await _repositoryWrapper.FligthRepository.GetFligthAdmin().SortDynamic(sort)
                    .ToDynamicListAsync<Fligth>())      
                : View(await _repositoryWrapper.FligthRepository.GetFligthAdminDisp(User.Identity.Name)
                    .SortDynamic(sort).ToDynamicListAsync<Fligth>());
        }
        
        // GET: Fligths/Details/5

        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fligth = await _repositoryWrapper.FligthRepository.GetFligthByIdAsync(id);
            if (fligth == null)
            {
                return NotFound();
            }

            return View(fligth);
        }

        [ForAdminDispatcher]
        // GET: Fligths/Create
        public IActionResult Create()
        {
            ViewData["FromCityId"] = _repositoryWrapper.CitiesRepository.SelectListCity();
            ViewData["WhereCityId"] = _repositoryWrapper.CitiesRepository.SelectListCity();
            return View();
        }

        // POST: Fligths/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Fligth fligth)
        {
            if (ModelState.IsValid)
            {
                if (fligth.Request.Message != "")
                    fligth.Request = new Request { Message = fligth.Request.Message, SignIn = User.Identity.Name };
                await _repositoryWrapper.FligthRepository.Create(fligth);
                return RedirectToAction(nameof(Index));
            }

            ViewData["FromCityId"] = _repositoryWrapper.CitiesRepository.SelectListCity(fligth.FromCityId);
            ViewData["WhereCityId"] = _repositoryWrapper.CitiesRepository.SelectListCity(fligth.WhereCityId);

            return View(fligth);
        }

        [ForAdmin]
        // GET: Fligths/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fligth = await _repositoryWrapper.FligthRepository.GetById(id);
            if (fligth == null)
            {
                return NotFound();
            }
            ViewData["FromCityId"] = _repositoryWrapper.CitiesRepository.SelectListCity(id);
            ViewData["WhereCityId"] = _repositoryWrapper.CitiesRepository.SelectListCity(id);
            return View(fligth);
        }

        // POST: Fligths/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name_Fligth,FromCityId,WhereCityId,DepartureDate,ArrivalDate,IsConfirmed,Price,Id")] Fligth fligth)
        {
            if (id != fligth.Id)
            {
                _logger.LogError($"Fligth with id: {id}, hasn't been found in db.");
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                _logger.LogError("Invalid owner object sent from client.");
                return View(fligth);
            }
            await _repositoryWrapper.FligthRepository.Update(id, fligth);
            var request = await _repositoryWrapper.RequsetRepository.GetRequestByIdAsync(id);
            if (request != null)
                await _repositoryWrapper.RequsetRepository.RemoveRequest(request);

            ViewData["FromCityId"] = _repositoryWrapper.CitiesRepository.SelectListCity(fligth.FromCityId);
            ViewData["WhereCityId"] = _repositoryWrapper.CitiesRepository.SelectListCity(fligth.FromCityId);
            return RedirectToAction(nameof(Index));
        }

        [ForAdmin]
        // GET: Fligths/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fligth = await _repositoryWrapper.FligthRepository.GetFligthByIdAsync(id);
            if (fligth == null)
            {
                return NotFound();
            }
            return View(fligth);
        }

        // POST: Fligths/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _repositoryWrapper.FligthRepository.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Represents is it user or not
        /// </summary>
        /// <returns></returns>
        private bool IsUser()
        {
            return !(User.IsInRole("admin") || User.IsInRole("dispatcher"));
        }
    }
}

Airline.UI/Controllers/SelectFligthTeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Airline.DAL.Airline_Db_Context;
using Airline.DAL.Models;
using Airline_Yurchenko.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Airline_Yurchenko.Controllers
{
    public class SelectFligthTeamController : Controller
    {
        private readonly AirlineContext _context;

        public SelectFligthTeamController(AirlineContext context)
        {
            _context = context;
        }
            

        [HttpGet]
        public IActionResult ListSelectTeamFligth(int? id)
        {
            var fligth = _context.Fligths.Include(e=> e.FligthTeams).SingleOrDefault(t => t.Id == id);
            var selectFligthId = fligth.FligthTeams.Select(e => e.Team_PersonId);
            var team = _context.Team_Persons;
            var model = new FligthListViewModels { Fligth = fligth};
            model.IsChoose = team.Where(t => selectFligthId.Contains(t.Id)).OrderBy(sort => sort.Name_Team);
            return View(model);
        }

        [HttpGet]
        public IActionResult Select(int? id)
        {
            var fligth = _context.Fligths.Include(e => e.FligthTeams).SingleOrDefault(t => t.Id == id);
            var selectFligthId = fligth.FligthTeams.Select(e => e.Team_PersonId);
            var team = _context.Team_Persons;
            var model = new FligthListViewModels { Fligth = fligth };
            model.IsChoose = team.Where(t => selectFligthId.Contains(t.Id)).OrderBy(sort => sort.Name_Team);
            model.NoChoose = team.Except(model.IsChoose).OrderBy(sort => sort.Name_Team);
            return View(model);
        }
        [HttpPost]
        public IActionResult Select(int fligthId, int[] IsChoose)
        {
            var fligth = _context.Fligths.Include(e => e.FligthTeams).SingleOrDefault(t => t.Id == fligthId);
            fligth.FligthTeams = new List<FligthTeam>();
            foreach (var discId in IsChoose)
            {
                fligth.FligthTeams.Add(new FligthTeam { FligthId = fligth.Id, Team_PersonId = discId });
            }
            _context.SaveChanges();
            return RedirectToAction(nameof(Select));
        }

    }
}

Airline.UI/Controllers/Team_PersonController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Airline.DAL.IRepository;
using Airline.DAL.Models;

namespace Airline_Yurchenko.Controllers
{
    public class Team_PersonController : Controller
    {
        private readonly ILoggerManager _logger;
        private readonly IRepositoryWrapper _repositoryWrapper;

        public Team_PersonController(IRepositoryWrapper repositoryWrapper, ILoggerManager logger)
        {
            _repositoryWrapper = repositoryWrapper;
            _logger = logger;
        }
        public IActionResult PersonalList()
        {
            return View();
        }

        // GET: Team_Person
        public IActionResult Index()
        {
            _logger.LogInfo($"Returned all team persons from database.");
            return View(_repositoryWrapper.TeamPersonRepository.Get());
        }
                      
        [HttpGet]
        public async Task <ActionResult> TeamDetails(int? id)
        {
            if (id == null)
            {
                _logger.LogError($"Team persons with id: {id}, hasn't been found in db.");
                return NotFound();
            }

            var teamPerson = await _repositoryWrapper.TeamPersonRepository.GetTeamByIdWithAllTeamAsync(id);

            if (teamPerson != null) return View(teamPerson);
            _logger.LogError($"Team persons not found");
            return NotFound();
        }
                                                             
        // GET: Team_Person/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                _logger.LogError($"Team persons with id: {id}, hasn't been found in db.");
                return NotFound();
            }

            var teamPerson = await _repositoryWrapper.TeamPersonRepository.GetById(id);
            if (teamPerson == null)
            {
                _logger.LogError($"Team persons not found");
                return NotFound();
            }

            return View(teamPerson);
        }

        // GET: Team_Person/Create
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name_Team,Id")] Team_Person teamPerson)
        {
            if (!ModelState.IsValid) 
                return View(teamPerson);
            _logger.LogInfo($"Team persons has been created into database.");
            await _repositoryWrapper.TeamPersonRepository.Create(teamPerson);
            return RedirectToAction(nameof(Index));
        }

        // GET: Team_Person/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                _logger.LogError($"Team persons id: {id}, hasn't been found in db.");
                return NotFound();
            }

            var teamPerson = await _repositoryWrapper.TeamPersonRepository.GetById(id);
            if (teamPerson == null)
            {
                _logger.LogError("Team persons object sent from client is null.");
                return NotFound();
            }
            return View(teamPerson);
        }

        // POST: Team_Person/Edit/5
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name_Team,Id")] Team_Person teamPerson)
        {
            if (id != teamPerson.Id)
            {
                _logger.LogError("Team persons object sent from client is null.");
                return NotFound();
            }

            if (!ModelState.IsValid) 
                return View(teamPerson);
            _logger.LogInfo("Team persons has been updated.");
            await _repositoryWrapper.TeamPersonRepository.Update(id, teamPerson);
            return RedirectToAction(nameof(Index));
        }

        // GET: Team_Person/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                _logger.LogError($"Team persons with id: {id}, hasn't been found in db.");
                return NotFound();
            }
            _logger.LogWarn($"Team persons with id: {id}, has been choose for delete.");
            var teamPerson = await _repositoryWrapper.TeamPersonRepository.GetById(id);
            if (teamPerson == null)
            {
                _logger.LogError("Invalid owner object sent from client.");
                return NotFound();
            }

            return View(teamPerson);
        }

        // POST: Team_Person/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _repositoryWrapper.TeamPersonRepository.Delete(id);
            
            return RedirectToAction(nameof(Index));
        }
        
    }
}

Airline.UI/Views/SelectFligthTeam/ListSelectTeamFligth.cshtml
@model Airline_Yurchenko.ViewModels.FligthListViewModels

@{
    ViewData["Title"] = "Select";
}

<h1 class="text-center pb-2">Teams for @Model.Fligth.Name_Fligth</h1>
<div class="container">
    @if (Model == null || Model.IsChoose.Count() == 0)
    {
        <div class="card m-2">
            <div class="card-body">
                <a class="btn btn-outline-success float-right " asp-controller="Fligths" asp-action="Index">Back to fly</a>
                <h4>Сommand is empty. <a class="text-primary" asp-controller="SelectFligthTeam" asp-action="Select" asp-route-id="@Model.Fligth.Id"> Create new?</a></h4>
            </div>
        </div>
    }
    else
    {
        <a class="btn btn-info mb-2" asp-controller="SelectFligthTeam" asp-action="Select" asp-route-id="@Model.Fligth.Id"> Add Teams </a>
        <a class="btn btn-outline-success float-right m-2" asp-controller="Fligths" asp-action="Index">Back to fly</a>

        <div class="card-group border border-bottom p-2 ">
            <form asp-action="ListSelectTeamFligth" method="post">
                @foreach (var item in Model.IsChoose)
                {
                    <a asp-controller="Team_Person" asp-action="TeamDetails" asp-route-id="@item.Id">
                        <div class="card float-left m-2 row-cols-4 ">
                            <img src="~/Content/Airline_Person/team.png" class="card-img-top" alt="Teams">
                            <div class="card-text">
                                <h4 class="card-title text-center"> @item.Name_Team</h4>
                            </div>
                        </div>
                    </a>
                }

                <input type="hidden" value="@Model.Fligth.Id" />
            </form>
        </div>
    }
</div>

Airline.UI/Views/SelectFligthTeam/Select.cshtml
@model Airline_Yurchenko.ViewModels.FligthListViewModels

@{
    ViewData["Title"] = "Select";
}


<h1 class="text-center"> Teams for @Model.Fligth.Name_Fligth</h1>
<div>
    <a class="btn btn-outline-success float-right m-2 mt-3" asp-controller="SelectFligthTeam" asp-action="ListSelectTeamFligth" asp-route-id="@Model.Fligth.Id">Back to List</a>
</div>
<div class="container border border-info m-2 ">

    <form asp-action="Select" method="post">
        @foreach (var item in Model.IsChoose)
        {
            <div class="checkbox form-check-inline m-2 ">
                <label class="btn btn-outline-primary ">
                    <input type="checkbox" name="IsChoose" value="@item.Id" checked>
                    @item.Name_Team
                </label>
            </div>
        }

        <hr/>

        @foreach (var item in Model.NoChoose)
        {
            <div class="checkbox form-check-inline m-2">
                <label class="btn btn-outline-dark">
                    <input type="checkbox" name="IsChoose" value="@item.Id">
                    @item.Name_Team
                </label>
            </div>
        }
        <div class="form-group text-center">
            <input type="submit" class="btn btn-info" value="Submit"/>
        </div>

        <input type="hidden" name="fligthId" value="@Model.Fligth.Id"/>
    </form>
    
</div>

Airline.UI/Views/SelectFligthTeam/SelectChoose.cshtml
@model Airline_Yurchenko.ViewModels.FligthListViewModels

@{
    ViewData["Title"] = "Select";
}

<h1>Select</h1>

<div class="container">
    <form asp-action="Select" method="post">
        @*@foreach (var item in Model.IsChoose)
        {
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="IsChoose" value="@item.Id" checked>
                    @item.Title
                </label>
            </div>
        }

        <hr />*@

        @foreach (var item in Model.NoChoose)
        {
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="IsChoose" value="@item.Id">
                    @item.Name_Team
                </label>
            </div>
        }
        <div class="form-group text-center">
            <input type="submit" class="btn btn-info" value="Submit" />
        </div>

        <input type="hidden" name="studentId" value="@Model.Fligth.Id" />
    </form>
</div>