Airline.UI/Controllers/Personal/NavigatorsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Airline.DAL.Airline_Db_Context;
using Airline.DAL.Models;
using Airline_Yurchenko.ViewModels;
using Airline.DAL.IRepository;
using Airline_Yurchenko.Areas.AccountFilters;
using Airline_Yurchenko.SortExtentions;

namespace Airline_Yurchenko.Controllers.Personal
{
    [ForAdmin]
    public class NavigatorsController : Controller
    {
        private readonly AirlineContext _context;
        private readonly IRepositoryWrapper _repositoryWrapper;
        
        public NavigatorsController(AirlineContext context, IRepositoryWrapper repositoryWrapper)
        {
            _context = context;
            _repositoryWrapper = repositoryWrapper;
        }
       
        // GET: Navigators
        public async Task<IActionResult> Index(string sort)
        {
            var users = _repositoryWrapper.NavigatorRepository.GetAllNavigator();
            sort ??= "Name";

            users = (IQueryable<Navigator>) users.SortDynamic(sort);

            return View(await users.ToListAsync());
            //return View(users.OrderByViaExpressions(sort).ToList());
        }

        // GET: Navigators/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var navigator = await _context.Navigators
                .Include(n => n.Team_Person)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (navigator == null)
            {
                return NotFound();
            }

            return View(navigator);
        }

        // GET: Navigators/Create
        public IActionResult Create()
        {
            ViewData["Team_PersonId"] = new SelectList(_context.Team_Persons, "Id", "Name_Team");
            return View();
        }

        // POST: Navigators/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Surname,Age,Experience,Salary,Team_PersonId,Id")] Navigator navigator)
        {
            if (ModelState.IsValid)
            {
                _context.Add(navigator);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Team_PersonId"] = new SelectList(_context.Team_Persons, "Id", "Name_Team", navigator.Team_PersonId);
            return View(navigator);
        }

        // GET: Navigators/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var navigator = await _context.Navigators.FindAsync(id);
            if (navigator == null)
            {
                return NotFound();
            }
            ViewData["Team_PersonId"] = new SelectList(_context.Team_Persons, "Id", "Name_Team", navigator.Team_PersonId);
            return View(navigator);
        }

        // POST: Navigators/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Surname,Age,Experience,Salary,Team_PersonId,Id")] Navigator navigator)
        {
            if (id != navigator.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(navigator);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NavigatorExists(navigator.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Team_PersonId"] = new SelectList(_context.Team_Persons, "Id", "Name_Team", navigator.Team_PersonId);
            return View(navigator);
        }

        // GET: Navigators/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var navigator = await _context.Navigators
                .Include(n => n.Team_Person)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (navigator == null)
            {
                return NotFound();
            }

            return View(navigator);
        }

        // POST: Navigators/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var navigator = await _context.Navigators.FindAsync(id);
            _context.Navigators.Remove(navigator);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // Checked add to table dublicate data
        public JsonResult ValidateJsonResultTitle(string surname)
        {
            if (_repositoryWrapper.NavigatorRepository.Get().Any(s => s.Surname == surname))
                return Json("title is not unique.");
            return Json(true);
        }
        private bool NavigatorExists(int id)
        {
            return _context.Navigators.Any(e => e.Id == id);
        }
    }
}

Airline.UI/Controllers/Personal/PilotsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Airline.DAL.IRepository;
using Airline.DAL.Models;
using Airline_Yurchenko.Areas.AccountFilters;
using Airline_Yurchenko.Helpers.Pagination;
using Airline_Yurchenko.SortExtentions;

namespace Airline_Yurchenko.Controllers.Personal
{
    [ForAdmin]
    public class PilotsController : Controller

    {
        private readonly ILoggerManager _logger;
        private readonly IRepositoryWrapper _repositoryWrapper;
        public PilotsController(IRepositoryWrapper repositoryWrapper, ILoggerManager logger)
        {
            _repositoryWrapper = repositoryWrapper;
            _logger = logger;
        }

        public IActionResult Index(int? company, string name, string sortOrder, int page = 1)
        {
            const int pageSize = 3;

            //фильтрация
            var users = _repositoryWrapper.PilotRepository.GetAllPilot();

            if (company != null && company != 0)
            {
                users = users.Where(p => p.Team_PersonId == company);
            }
            if (!String.IsNullOrEmpty(name))
            {
                users = users.Where(p => p.Name.Contains(name));
            }
            sortOrder ??= "Name";
            // сортировка
            users = (IQueryable<Pilot>) users.SortDynamic(sortOrder); //используем ранее созданный метод расширения 
            // пагинация
            var count = users.Count();
            var items = users.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            // формируем модель представления
            var viewModel = new IndexViewModel
            {
                PageViewModel = new PageViewModel(count, page, pageSize),
                FilterViewModel = new FilterViewModel(_repositoryWrapper.TeamPersonRepository.Get().ToList(), company, name),
                Users = items
            };
            return View(viewModel);
        }
     
        //private static IQueryable<Pilot> Queryable(SortState sortOrder, IQueryable<Pilot> users)
        //{
        //    users = sortOrder switch
        //    {
        //        SortState.NameDesc => users.OrderByDescending(s => s.Name),
        //        SortState.AgeAsc => users.OrderBy(s => s.Age),
        //        SortState.AgeDesc => users.OrderByDescending(s => s.Age),
        //        SortState.CompanyAsc => users.OrderBy(s => s.Team_Person.Name_Team), ////????
        //        SortState.CompanyDesc => users.OrderByDescending(s => s.Team_Person.Name_Team) ////??????
        //        ,
        //        _ => users.OrderBy(s => s.Name)
        //    };

        //    return users;
        //}
        
        // GET: Pilots/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                _logger.LogError($"Pilot with id: {id}, hasn't been found in db.");
                return NotFound();
            }
            _logger.LogInfo($"Returned owner with id: {id}");
            var pilot = await _repositoryWrapper.PilotRepository.GetPilotcByIdWithTeamAsync(id);
            if (pilot == null)
            {
                _logger.LogError($"Pilot not found");
                return NotFound();
            }

            return View(pilot);
        }

        // GET: Pilots/Create
        public IActionResult Create()
        {
            ViewData["Team_PersonId"] = _repositoryWrapper.TeamPersonRepository.SelectListTeamName();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Pilot pilot)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Team_PersonId"] = _repositoryWrapper.TeamPersonRepository.SelectListTeamName(pilot.Team_PersonId);
                return View(pilot);
            }

            _logger.LogInfo($"Pilot has been created into database.");
            await _repositoryWrapper.PilotRepository.CreateWithImage(pilot);
            return RedirectToAction(nameof(Index));
        }

        // GET: Pilots/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                _logger.LogError("Pilot object sent from client is null.");
                return NotFound();
            }

            var pilot = await _repositoryWrapper.PilotRepository.GetById(id);
            if (pilot == null)
            {
                _logger.LogError($"Pilot with id: {id}, hasn't been found in db.");
                return NotFound();
            }

            ViewData["Team_PersonId"] = _repositoryWrapper.TeamPersonRepository.SelectListTeamName(id);
            return View(pilot);
        }

        // POST: Pilots/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Pilot pilot)
        {
            if (id != pilot.Id)
            {
                _logger.LogError($"Pilot with id: {id}, hasn't been found in db.");
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                _logger.LogError("Invalid owner object sent from client.");
                return View(pilot);
            }

            ViewData["Team_PersonId"] = _repositoryWrapper.TeamPersonRepository.SelectListTeamName(pilot.Team_PersonId);
            await _repositoryWrapper.PilotRepository.GetByIdWithImage(id, pilot);
            return RedirectToAction(nameof(Index));

        }

        // GET: Pilots/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                _logger.LogError($"Pilot with id: {id}, hasn't been found in db.");
                return NotFound();
            }

            var pilot = await _repositoryWrapper.PilotRepository
                .GetPilotcByIdWithTeamAsync(id); // await _context.Pilots

            if (pilot == null)
            {
                _logger.LogError($"Pilot with id: {id}, hasn't been found in db.");
                return NotFound();
            }
            _logger.LogWarn($"Pilot with id: {id}, has been choose for delete.");
            return View(pilot);
        }

        // POST: Pilots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            _logger.LogInfo($"Pilot has been deleted from database.");
            await _repositoryWrapper.PilotRepository.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

Airline.UI/Controllers/Personal/Radio_operatorController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Airline.DAL.Airline_Db_Context;
using Airline.DAL.Models;
using Airline_Yurchenko.Areas.AccountFilters;

namespace Airline_Yurchenko.Controllers.Personal
{
    [ForAdmin]
    public class Radio_operatorController : Controller
    {
        private readonly AirlineContext _context;

        public Radio_operatorController(AirlineContext context)
        {
            _context = context;
        }

        // GET: Radio_operator
        public async Task<IActionResult> Index()
        {
            var airlineContext = _context.Radio_Operators.Include(r => r.Team_Person);
            return View(await airlineContext.ToListAsync());
        }

        // GET: Radio_operator/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var radio_operator = await _context.Radio_Operators
                .Include(r => r.Team_Person)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (radio_operator == null)
            {
                return NotFound();
            }

            return View(radio_operator);
        }

        // GET: Radio_operator/Create
        public IActionResult Create()
        {
            ViewData["Team_PersonId"] = new SelectList(_context.Team_Persons, "Id", "Name_Team");
            return View();
        }

        // POST: Radio_operator/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Surname,Age,Experience,Salary,Team_PersonId,Id")] Radio_operator radio_operator)
        {
            if (ModelState.IsValid)
            {
                _context.Add(radio_operator);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Team_PersonId"] = new SelectList(_context.Team_Persons, "Id", "Name_Team", radio_operator.Team_PersonId);
            return View(radio_operator);
        }

        // GET: Radio_operator/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var radio_operator = await _context.Radio_Operators.FindAsync(id);
            if (radio_operator == null)
            {
                return NotFound();
            }
            ViewData["Team_PersonId"] = new SelectList(_context.Team_Persons, "Id", "Name_Team", radio_operator.Team_PersonId);
            return View(radio_operator);
        }

        // POST: Radio_operator/Edit/5
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Surname,Age,Experience,Salary,Team_PersonId,Id")] Radio_operator radio_operator)
        {
            if (id != radio_operator.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                ViewData["Team_PersonId"] =
                    new SelectList(_context.Team_Persons, "Id", "Name_Team", radio_operator.Team_PersonId);
                return View(radio_operator);
            }

            try
            {
                _context.Update(radio_operator);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!Radio_operatorExists(radio_operator.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Radio_operator/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var radio_operator = await _context.Radio_Operators
                .Include(r => r.Team_Person)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (radio_operator == null)
            {
                return NotFound();
            }

            return View(radio_operator);
        }

        // POST: Radio_operator/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var radio_operator = await _context.Radio_Operators.FindAsync(id);
            _context.Radio_Operators.Remove(radio_operator);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Radio_operatorExists(int id)
        {
            return _context.Radio_Operators.Any(e => e.Id == id);
        }
    }
}

Airline.UI/Views/Team_Person/Create.cshtml
@model Airline.DAL.Models.Team_Person

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Team_Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name_Team" class="control-label"></label>
                <input asp-for="Name_Team" class="form-control" />
                <span asp-validation-for="Name_Team" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-info" asp-action="Index">Back to List</a>
</div>

Airline.UI/Views/Team_Person/Delete.cshtml
@model Airline.DAL.Models.Team_Person

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Team_Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name_Team)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name_Team)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Airline.UI/Views/Team_Person/Details.cshtml
@model Airline.DAL.Models.Team_Person

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Team_Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name_Team)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name_Team)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Airline.UI/Views/Team_Person/Edit.cshtml
@model Airline.DAL.Models.Team_Person

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Team_Person</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name_Team" class="control-label"></label>
                <input asp-for="Name_Team" class="form-control" />
                <span asp-validation-for="Name_Team" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Airline.UI/Views/Team_Person/Index.cshtml
@model IEnumerable<Airline.DAL.Models.Team_Person>

@{
    ViewData["Title"] = "Index";
}

<h1 class="text-center">Team Person</h1>

<a class="btn btn-primary btn-info mb-2" asp-action="Create">Create New</a>

<table class="table border">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name_Team)
            </th>
            <th>Operations</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td class="font-weight-bold">
                @Html.DisplayFor(modelItem => item.Name_Team)
            </td>
            <td>
                <a class="btn btn-info" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

Airline.UI/Views/Team_Person/PersonalList.cshtml
@{
    ViewBag.Title = "Flitht_Teams";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="text-center">Flight Teams</h1>
<br />
    <div class="float-left" style="max-width: 540px;">
        <div class="row no-gutters">
            <div class="col-lg-4 ">
                <div class="Myclass">
                    <div class="Button_Create">
                        <a href="@Url.Action("Index","Radio_operator")"> <img src="@Url.Content("~/Content/Airline_Person/Steward.png")" alt="Home" width="150" height="150" card-img /></a>
                    </div>
                
                </div>
            </div>
            <div class="col-lg-8 ">
                <div class="card-body">
                    <h4 class="card-title ">Radio Operator</h4>
                    <p class="card-text">A navigator is the person on board a ship or aircraft responsible for its navigation. Broadcast weather reports and warnings. The navigator's primary responsibility is to be aware of ship or aircraft position at all times. </p>
                    <p class="card-text"><small class="text-muted"> </small></p>
                </div>
            </div>
        </div>
    </div>

    <div class="float-right " style="max-width: 540px;">
        <div class="row no-gutters">
            <div class="col-lg-4">
                <div class="Button_Create">
                    <a href="@Url.Action("Index","Stewardesses")"> <img src="@Url.Content("~/Content/Airline_Person/stewardess.png")" alt="Home" width="150" height="150" card-img /></a>
                </div>
                
            </div>
            <div class="col-lg-8">
                <div class="card-body">
                    <h4 class="card-title">Stewardess</h4>
                    <p class="card-text">Flight attendants or cabin crew are members of an aircrew employed by airlines primarily to ensure the safety and comfort of passengers aboard commercial flights, on select business jet aircraft, and on some military aircraft.</p>
                    <p class="card-text"><small class="text-muted"></small></p>
                </div>
            </div>
        </div>
    </div>

    <br />
    <br />
    <br />

    <div class="float-left " style="max-width: 540px;">
        <div class="row no-gutters">
            <div class="col-lg-4 ">
                <div class="Button_Create">
                    <a href="@Url.Action("Index","Pilots","")"> <img src="@Url.Content("~/Content/Airline_Person/pilot1.png")" alt="Home" width="150" height="150" card-img /></a>
                </div>

            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h4 class="card-title">Pilot</h4>
                    <p class="card-text">An aircraft pilot or aviator is a person who controls the flight of an aircraft by operating its directional flight controls. Must have legal right to live and work in Europe.</p>
                    <p class="card-text"><small class="text-muted"></small></p>
                </div>
            </div>
        </div>
    </div>

    <div class="float-right" style="max-width: 540px;">
        <div class="row no-gutters">
            <div class="col-lg-4">
                <div class="Button_Create">
                    <a href="@Url.Action("Index","Navigators","")"> <img src="@Url.Content("~/Content/Airline_Person/Radio.png")" alt="Home" width="150" height="150" card-img /></a>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card-body">
                    <h5 class="card-title">Dispatcher</h5>
                    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. A flight dispatcher assists in planning flight paths and other conditions. </p>
                    <p class="card-text"><small class="text-muted"></small></p>
                </div>
            </div>
        </div>
    </div>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

Airline.UI/Views/Team_Person/TeamDetails.cshtml
@using Airline.DAL.Models

    @model Airline.DAL.Models.Team_Person

    @{

        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    <br />
    @Html.HiddenFor(model => model.Id)
    <div>
        <div class="text-center ">
            <h1 style="font-family:'Comic Sans MS'">
                <img src="~/Content/Airline_Person/team.png" width="50" height="50" />
                Flight Team
                <img src="~/Content/Airline_Person/team.png" width="50" height="50" />
            </h1>
        </div>
        <hr />
    </div>

    <table class="table border">
        <thead>
            <tr>
                <th style="font-family:'Comic Sans MS'">   @Html.DisplayFor(model => model.Name_Team)</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Experience</th>
                <th>Age</th>
                <th>Salary</th>
            </tr>
        </thead>
        <tbody>

            <tr>
                @foreach (Navigator navigator in Model.Navigators)
                {
                    <th>  <img src="~/Content/Airline_Person/Radio.png" width="45" height="45" alt="Navigator" />Dispatcher</th>

                    <td>@navigator.Name</td>
                    <td> @navigator.Surname</td>
                    <td> @navigator.Experience Year</td>
                    <td> @navigator.Age</td>
                    <td> @navigator.Salary $</td>
                }
            </tr>

            <tr>
                @foreach (Pilot pilot in Model.Pilots)
                {
                    <th><img src="~/Content/Airline_Person/pilot1.png" width="45" height="45" alt="Pilot" />Pilot</th>

                    <td>@pilot.Name</td>
                    <td>@pilot.Surname</td>
                    <td>@pilot.Experience Year</td>
                    <td>@pilot.Age</td>
                    <td>@pilot.Salary $</td>
                }
            </tr>

            <tr>
                <th><img src="~/Content/Airline_Person/stewardess.png" width="45" height="45" alt="Stewardess" />Stewardess</th>

                @foreach (Stewardess stewardess in Model.Stewardesses)
                {
                    <td>@stewardess.Name </td>
                    <td>@stewardess.Surname </td>
                    <td>@stewardess.Experience Year</td>
                    <td>@stewardess.Age </td>
                    <td>@stewardess.Salary $ </td>
                }
            </tr>

            <tr>
                <th><img src="~/Content/Airline_Person/Steward.png" width="45" height="45" alt="Radio_operator" />Radio_operator</th>

                @foreach (Radio_operator radio_Operator in Model.Radio_Operators)
                {
                    <td> @radio_Operator.Name </td>
                    <td> @radio_Operator.Surname </td>
                    <td> @radio_Operator.Experience Year     </td>
                    <td> @radio_Operator.Age </td>
                    <td> @radio_Operator.Salary $</td>
                }
            </tr>
        </tbody>
    </table>